spring:

#  You can configure this in the configuration file or using Bean and the builder object in the AiChatClientConfig.java file in the config package
#  Only then you have to change the dependency in pom.xml from <spring-ai-openai-spring-boot-starter> to <spring-ai-openai>
#  ai:
#    openai:
#      api-key: ${OPENAI_API_KEY}
#      chat:
#  All properties prefixed with spring.ai.openai.chat.options can be overridden at runtime by adding a request specific Chat Options to the Prompt call.
#        options:
#          model: gpt-3.5-turbo
#          max-tokens: 150
#          temperature: 0

#  You can configure this in the configuration file or using Bean and the builder object in the AiChatClientConfig.java file in the config package
#  Only then you have to change the dependency in pom.xml from <spring-ai-azure-openai-spring-boot-starter> to <spring-ai-azure-openai>
#  ai:
#    azure:
#      openai:
#        api-key: YOUR_API_KEY
#        endpoint: YOUR_ENDPOINT
#        chat:
# All properties prefixed with spring.ai.azure.openai.chat.options can be overridden at runtime by adding a request specific Chat Options to the Prompt call.
#          options:
#            model: gpt-3.5-turbo
#            max-tokens: 150
#            temperature: 0

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#  Only to pull out the token in the bean, naming arbitrary
  openai:
    api-key: ${OPENAI_API_KEY}

#  Only to pull out the token and endpoint in the bean, naming arbitrary
#  azure:
#    openai:
#      api-key: YOUR_API_KEY
#      endpoint: YOUR_ENDPOINT

# Supported database types are available in the SupportedDbType.java enums package
  data-sources:
    db1:
      url: jdbc:postgresql://localhost:5432/marketplace
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
      type: postgresql
    db2:
      url: jdbc:oracle:thin:@localhost:1521/FREE
      username: system
      password: my_password
      driver-class-name: oracle.jdbc.OracleDriver
      type: oracle
    db3:
      url: jdbc:mysql://localhost:3306/my_database
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: mysql
